baseURL = 'https://dimiro1.dev/'
languageCode = 'en-US'
title = 'DIMIRO1.DEV'

[params]
  label = 'Engineering_Notes'
  tagline = 'Software Engineer, focusing on high-performance systems and functional paradigms.'
  description = 'Personal blog about software engineering, functional programming, and system design.'
  github = 'https://github.com/dimiro1'

[menus]
  [[menus.main]]
    name = 'Archive'
    pageRef = '/posts'
    weight = 10

  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 20

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    tabWidth = 4

[pagination]
  pagerSize = 10

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
